name: CI

on: [push]

jobs:

  Build:
    runs-on: ubuntu-latest
    container: node:10-alpine

    steps: 
      - uses: actions/checkout@v1

      - name: Build and Push Backend Image
        env: 
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo "${GCLOUD_SERVICE_KEY}" | docker login -u _json_key --password-stdin https://gcr.io
          cd site-backend
          docker build . -t gcr.io/stackmapper/backend
          docker push gcr.io/stackmapper/backend

      - name: Install Dependencies
        run: yarn install

      - name: Build Site Frontend
        env: 
          API_URL: https://us-central1-stackmapper.cloudfunctions.net
        run: |
          cd site-frontend
          yarn ci:build

      - name: Upload Site Frontend Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: frontend-artifact
          path: site-frontend/build

  Deploy:
    runs-on: ubuntu-latest
    container: google/cloud-sdk:alpine
    needs: Build

    steps:
      - uses: actions/checkout@v1

      - name: Init Gcloud CLI
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo ${GCLOUD_SERVICE_KEY} > ./keyfile.json
          gcloud auth activate-service-account --key-file ./keyfile.json

      - name: Download Site Frontend Artifacts
        uses: actions/download-artifact@v1
        with:
          name: frontend-artifact

      - name: Deploy Site Frontend
        run: gsutil rsync -d -r frontend-artifact gs://www.stackmapper.com   

      - name: Deploy Site Backend
        run: |
          gcloud beta run deploy stackmapper-backend --project stackmapper --image gcr.io/stackmapper/backend --region us-west1 --allow-unauthenticated --platform managed
