name: CI

on: [push]

jobs:

  Build:
    runs-on: ubuntu-latest
    container: node:10-alpine

    steps: 
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build Site Frontend
        env: 
          API_URL: https://us-central1-stackmapper.cloudfunctions.net
        run: |
          cd site-frontend
          yarn ci:build

      - name: Upload Site Frontend Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: frontend-artifact
          path: site-frontend/build

  Deploy:
    runs-on: ubuntu-latest
    container: google/cloud-sdk:alpine
    needs: Build

    steps:
      - uses: actions/checkout@v1

      - name: Init Gcloud CLI
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo ${GCLOUD_SERVICE_KEY} > ./keyfile.json
          gcloud auth activate-service-account --key-file ./keyfile.json

      - name: Download Site Frontend Artifacts
        uses: actions/download-artifact@v1
        with:
          name: frontend-artifact

      - name: Deploy Site Frontend
        run: gsutil rsync -d -r frontend-artifact gs://www.stackmapper.com   

      - name: Deploy Site Backend
        run: |
          cd site-backend
          gcloud functions deploy transform --project stackmapper --runtime nodejs10 --entry-point transform --trigger-http --allow-unauthenticated
